Scenario 1
EIivaras/Merfolk_Campaign pull request #6
Opened 2021-07-17 00:11 UTC by EIivaras

2021-07-17 12:12 UTC, Descacharrado commented on scenarios/01_a_patrol_gone_awry.cfg
> +			[filter_side]
Now shroud is removed in a circle instead of an array

2021-07-17 12:14 UTC, Descacharrado commented on scenarios/01_a_patrol_gone_awry.cfg
> +		[/lift_fog]
Added animation for Naga warrior, removed animate=yes atribute

2021-07-17 12:14 UTC, Descacharrado commented on scenarios/01_a_patrol_gone_awry.cfg
> +		[/unit]
Added a Macro that does what lines 360 to 373 does, animating an appearing unit, will be very useful for future scenarios

2021-07-17 12:19 UTC, Descacharrado requested changes
Several comments added on scenario and utils file, pot and ring seem to not be working. Has to be reviewed by mirion too.

2021-07-17 12:19 UTC, Descacharrado commented on scenarios/01_a_patrol_gone_awry.cfg
> +
Potion and ring events seem to work only once, as I can see in the code, these events are supposed to work several times if not taken, should be reviewed before merge and Q&A

2021-07-17 22:06 UTC, Mirion147 commented on scenarios/01_a_patrol_gone_awry.cfg
> +		[/unit]
I would just suggest notating where the macro is located in case we ever need to adjust it (or if we adjust it later)

2021-07-17 22:23 UTC, Mirion147 reviewed
Do we want the dolphin tail to have the stun ability that I think the Brawlers have? Kinda like, "this is where they learned this attack" sort of a thing.

2021-07-17 22:23 UTC, Mirion147 commented on scenarios/01_a_patrol_gone_awry.cfg
> +		[filter]
Need to add side=1 to this filter

2021-07-17 22:23 UTC, Mirion147 commented on scenarios/01_a_patrol_gone_awry.cfg
> +			[variable]
This should be the ring_visited variable

2021-07-17 22:23 UTC, Mirion147 commented on scenarios/01_a_patrol_gone_awry.cfg
> +		[filter]
This needs to be adjusted to be for the ring at 5,5 and the following variables need to be switched to the ring as well

2021-07-17 22:23 UTC, Mirion147 commented on scenarios/01_a_patrol_gone_awry.cfg
> +					{POTION_OF_VITALITY}
We need to add code to remove the image after the potion is picked up, probs to the util here

2021-07-17 22:23 UTC, Mirion147 commented on scenarios/01_a_patrol_gone_awry.cfg
> +	[event]
I'm assuming this is preemptive of dialog?

2021-07-17 22:23 UTC, Mirion147 commented on scenarios/01_a_patrol_gone_awry.cfg
> +	[event]
Don't need "" when using IDs, can just do id=kai, but anyway, do we feel like it's best to have them notice this when they get there? Or perhaps have it be a sighted event where the kai is moved onto the keep and then the dialog begins?

2021-07-17 22:23 UTC, Mirion147 commented on units/Dolphin.cfg
> +    [attack]
that waterspray shriek tho XD

2021-07-17 22:23 UTC, Mirion147 commented on utils/utils.cfg
> +	    [remove_item]
This isn't working, I guess?

2021-07-18 00:26 UTC, EIivaras commented on scenarios/01_a_patrol_gone_awry.cfg
> +	[event]
Mmmm that's an interesting idea. I think I'll throw that in at some point.

2021-07-18 00:26 UTC, EIivaras commented on scenarios/01_a_patrol_gone_awry.cfg
> +	[event]
Nah, that was actually a mistake by me -- I should have taken that out when I reworked the event, classic copy + paste error.

2021-07-18 00:29 UTC, EIivaras commented on scenarios/01_a_patrol_gone_awry.cfg
> +					{POTION_OF_VITALITY}
Good point, I've added this to my next comit.

2021-07-18 00:29 UTC, EIivaras commented on scenarios/01_a_patrol_gone_awry.cfg
> +		[filter]
Yep, excellent catch! Classic copy + paste error.

2021-07-18 00:29 UTC, EIivaras commented on scenarios/01_a_patrol_gone_awry.cfg
> +			[variable]
Good catch!

2021-07-18 00:29 UTC, EIivaras commented on scenarios/01_a_patrol_gone_awry.cfg
> +		[filter]
Resolved in the commit I'm working on!

2021-07-18 00:30 UTC, EIivaras commented on scenarios/01_a_patrol_gone_awry.cfg
> +
Yep, fixed a bunch of bugs to do with this thanks to Mirion's help.

2021-07-18 00:30 UTC, EIivaras commented on utils/utils.cfg
> +	    [remove_item]
I guess not :(

2021-07-28 21:05 UTC, Descacharrado commented on scenarios/01_a_patrol_gone_awry.cfg
> +
Added the macro that solves the problem

2021-07-28 21:07 UTC, Descacharrado commented on utils/utils.cfg
> +	    [remove_item]
It is working (now at least, gameplay tested).

2021-07-28 21:13 UTC, Descacharrado commented on utils/utils.cfg
> +#util7
This is the macro that handles this kind of moveto events which have potions, rings, capes, storm tridents etc. Basically it uses only one variable which should be defined in VARIABLE_NAME which can have the values of no (if it has not been visited) yes (if it has been visited) or done (if it has been taken). x, y, side and race are for filters and can be a list of values. MSG_ACCEPT should be a string ( _ "message") for when the player is going to accept the item, MSG_REJECT is similar. EFFECT_WML is where the effect should be put in, it can be done by having another [object] macro and putting it in, but in that case IS_TRIDENT has to be defined as yes (maybe I should change that to IS_OBJECT), eitherway it has to be defined as any other thing that is not "yes" (like, for example, "no") if you only want to write code inside a predefined [object] space. Last but not least, all the event messages and removal of objects should be coded in the ADITIONAL_EVENT_WML

2021-07-28 21:17 UTC, Descacharrado approved these changes
With those changes I approve for Q&A testing. I think dialog is yet to be decided but gameplay should be up and running.

2021-08-02 16:50 UTC, Descacharrado approved these changes
Fixed potion and ring events while making the macro more understandable in regard to the values and name the variable holding the status of the event has.

2021-08-31 00:33 UTC, merged