Feature/scenario2
EIivaras/Merfolk_Campaign pull request #9
Opened 2021-08-10 12:22 UTC by Descacharrado

Scenario 2 is ready for merge into develop and QA, should be working with S01. Perharps the leader definition must be tweaked a bit to use the custom Kai Danielle instead of a normal initiate when in develop.

2021-08-10 12:28 UTC, Descacharrado commented on _main.cfg
This and other conflicts should be resolved when merging.

2021-09-01 23:35 UTC, EIivaras reviewed
Some clean-up, praise and a few questions!

2021-09-01 23:35 UTC, EIivaras commented on utils/items.cfg
> +#define STORM_TRIDENT X Y ID
Would it make sense to move the ring & potion to this file as well?

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +    name= _ "Too many Naga"
It's probably worth discussing a different scenario title for this one -- while "too many naga" gets the point across, it feels like the title of a YT vid rather than an official scenario name.

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +    map_file=02_Too_many_Naga.map
Whatever we end up going with for the scenario name, we should keep the map file name lowercase for consistency.

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +
```suggestion
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +		[/ai]
```suggestion
	[ai]
    		[goal]
        		name=target_location
        		[criteria]
            		x,y=19,1
        		[/criteria]
#ifdef EASY
        		value=1
#endif
#ifdef NORMAL
        		value=3
#endif
#ifdef HARD
        		value=5
#endif
    		[/goal]
	[/ai]
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +		[/ai]
```suggestion
	[ai]
    		[goal]
        		name=target_location
        		[criteria]
            		x,y=19,1
        		[/criteria]
#ifdef EASY
        		value=1
#endif
#ifdef NORMAL
        		value=3
#endif
#ifdef HARD
        		value=5
#endif
    		[/goal]
	[/ai]
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +        [/objectives]
```suggestion
        name=prestart

	##Number of enemies escaping variable
#ifdef EASY
	{VARIABLE noee 10}
#endif
#ifdef NORMAL
	{VARIABLE noee 7}
#endif
#ifdef HARD
	{VARIABLE noee 3}
#endif
	[objectives]
            side=1
            [objective]
                condition=win
                description= _ "Defeat the enemy leaders"
            [/objective]
            [objective]
                condition="lose"
                description= _ "$noee enemies flee north"
            [/objective]
            [objective]
		# TODO: Change names when finalized
                description= _ "Death of Danielle, SupportingCharacter1 and SupportingCharacter2"
                condition="lose"
            [/objective]
            {TURNS_RUN_OUT}
            [gold_carryover]
                bonus=yes
                carryover_percentage=40
            [/gold_carryover]
            note= _ "Explore!"
      [/objectives]
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +            message= _ "You won't find one these in the mud."
```suggestion
            message= _ "Wait, what's this? There's a... trident of some sort in the mud! Should I pick it up?"
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +				[/command]
```suggestion
              [command]
			[set_variable]
				name=get_trident
				value=visited
			[/set_variable]
		[/command]
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +            message= _ "Whoa, what is such a big looking tree doing here, in the middle of the ocean?."
```suggestion
            message= _ "Whoa, what is such a big looking tree doing here, in the middle of the ocean?"
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +            message= _ "I feel like the tree is calling upon me"
```suggestion
            message= _ "I feel like the tree is calling to me."
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +				[/command]
```suggestion
              [command]
			[set_variable]
				name=get_buff
				value=visited
			[/set_variable]
		[/command]
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +                label= _ "Oh no, I do not like this feeling."
```suggestion
                label= _ "I've got a bad feeling about this... no way I'm resting here!"
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +            	message= _ "I feel... powerful"
```suggestion
            	message= _ "I feel... strange. Powerful, even!"
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +            	message= _ "$unit.name obtained +1 ranged damage"
```suggestion
            	message= _ "$unit.name obtained +1 ranged damage!"
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +    {VIU_LAST_BREATH Danielle (_ "Oh, I die... I failed as a Kai to all of the mermen.")}
```suggestion
    {VIU_LAST_BREATH Danielle (_ "No! My people need me... and I've failed them!")}
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +    	{UNIT 3 (Naga Warrior) 1 36 ()}
Should we spice it up a bit more, rather than having just naga warriors here?

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +    		message= _ "We have arrived, chief"
```suggestion
    		message= _ "We have arrived, chief."
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +    		message= _ "Hahahaha ssssssee you later"
```suggestion
    		message= _ "Foolish mermaid. You shouldn't have tried to stop us!"
```

2021-09-01 23:35 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +    		message= _ "Ssssscya"
```suggestion
    		message= _ "With me, soldiers!"
```

2021-09-01 23:35 UTC, EIivaras commented on utils/utils.cfg
> +
Love these added macros. Great stuff!

2021-09-01 23:38 UTC, EIivaras commented on scenarios/02_Too_many_Naga.cfg
> +        [message]
As a thought... would it make sense to give this event a bit more lore, and perhaps foreshadow? The tree itself could talk to us (or a level 4 elf mage, the faerie, could come out for this scene) about a sense of impending doom and/or corruption.

Something like "I can feel it in the air... and in [my/the tree's] roots... something isn't right. The land is tainted, but with what, I can't say..."

This gives us the opportunity to set it up even more.

2021-09-02 12:17 UTC, Descacharrado commented on utils/items.cfg
> +#define STORM_TRIDENT X Y ID
Yeah, that would probably fit. Maybe when we review first 3 scenarios alltogether we can tweak that kind of organization stuff.

2021-09-02 12:20 UTC, Descacharrado commented on scenarios/02_Too_many_Naga.cfg
> +        [message]
A good point for the S02 story review meeting

2021-09-02 12:22 UTC, Descacharrado commented on scenarios/02_Too_many_Naga.cfg
> +    name= _ "Too many Naga"
Totally agree, that will have to be decided in the story meeting perhaps.

2021-09-02 12:26 UTC, Descacharrado commented on scenarios/02_Too_many_Naga.cfg
> +    	{UNIT 3 (Naga Warrior) 1 36 ()}
Sure thing!

2021-09-14 21:09 UTC, Mirion147 requested changes

2021-09-14 21:09 UTC, Mirion147 commented on scenarios/02_Too_many_Naga.cfg
> +    map_file=02_too_many_naga.map
This title is correctly displayed here, but the map title is "Too_many_Naga" with caps, and should be changed to match here.

2021-09-14 21:09 UTC, Mirion147 commented on scenarios/02_Too_many_Naga.cfg
> +    [item]
Nitpick of can be x,y=7,6. Not necessary, but I'm here so I'm throwing the comment out here.

2021-09-14 21:09 UTC, Mirion147 commented on scenarios/02_Too_many_Naga.cfg
> +		[objectives]
So, in game, I had I think 4 enemies flee, the condition shifted to a winning condition "when 3 enemies flee" or something, though I still lost when 7 fled. I'm looking for a more specific reason for the problem.

Is there a reason why "lose" is quoted?

Add "delayed_variable_substitution=yes" into the objectives tag:
[objectives]
side=1
delayed_yada_yada
[objective]
...
[/objectives]

2021-09-14 21:09 UTC, Mirion147 commented on scenarios/02_Too_many_Naga.cfg
> +        [filter]
This filter can probably have side=1 removed as there are no other mermen, but this is another nitpick.

2021-09-14 21:09 UTC, Mirion147 commented on scenarios/02_Too_many_Naga.cfg
> +    	[filter]
Is there a reason that everything is specific to this tile? Even with a 2 tile radius, a player who has peeked into the code can easily place merfolk on these tiles and leave them here throwing the difficulty of this scenario way out of whack. Could we just remove the X= coordinate and leave it as just Y=1, so the whole top strip?

2021-09-14 21:09 UTC, Mirion147 commented on scenarios/02_Too_many_Naga.cfg
> +    	[objectives]
I'm not sure why this is here, is it to update the count as naga leave? Either way, this is the problem with the condition because noee is set as a win condition. You can avoid having this in here at all though by adding 
delayed_variable_substitution=yes
into the top objectives tag. I'll add it there as well.

2021-09-14 22:02 UTC, Descacharrado commented on scenarios/02_Too_many_Naga.cfg
> +    [item]
Done

2021-09-14 22:03 UTC, Descacharrado commented on scenarios/02_Too_many_Naga.cfg
> +    map_file=02_too_many_naga.map
We will fix this utterly when we change the scenario name.

2021-09-14 22:04 UTC, Descacharrado commented on scenarios/02_Too_many_Naga.cfg
> +		[objectives]
Fixed!

2021-09-14 22:04 UTC, Descacharrado commented on scenarios/02_Too_many_Naga.cfg
> +        [filter]
True, done

2021-09-14 22:09 UTC, Descacharrado commented on scenarios/02_Too_many_Naga.cfg
> +    	[filter]
The whole upper line would be hard to defend imho, the purpose (in my head at least) is for the player to get out of their confort and put units in deep water, having to defend without being able to retreat too much during nights. Also, It is true that anyone could peek in the code to look at the location and I saw that as a problem so I added a signpost so it clearer for the player for where the naga will flee. I inspired myself in S21 of Delfadors Memoirs "Clash at the Manor" which does something similar. If you still disagree we can have a more in detail discussion about it.

2021-09-14 22:19 UTC, Mirion147 commented on scenarios/02_Too_many_Naga.cfg
> +    	[filter]
Idk if I ever finished DM and definitely don't remember the scenario lol, but that's fine. If you have a plan in mind then I'm with it, just wasn't sure what was going on. If there are other comments about it from other people then I'll join the discussion, but if everyone else is fine with it then I don't have enough of an issue with it to push for a change.

2021-09-19 09:43 UTC, Descacharrado commented on scenarios/02_Too_many_Naga.cfg
> +    	[filter]
Fixed with the new update

2021-09-19 09:44 UTC, Descacharrado commented on scenarios/02_Too_many_Naga.cfg
> +    	[objectives]
Solved

2021-09-19 14:42 UTC, ArchangeLillith approved these changes

2021-09-20 14:52 UTC, Mirion147 commented on scenarios/02_along_the_way.cfg
> +                            message= _ "We have to defend the north route!"
Might want to switch this to -northern- route

2021-09-20 14:53 UTC, Mirion147 approved these changes

2021-09-20 23:21 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +            story= _ "With the last naga defeated, Danielle and her party started their journey back east, to Elefas."
```suggestion
            story= _ "With the of the last naga defeated, Danielle and her retinue started their journey northeast, back to Elefas."
```

If the naga are moving north to get to Elefas, it would not make sense to say the Danielle's retinue is moving west to east. There needs to be a component of them moving north.

2021-09-20 23:22 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +        	story= _ "But they came across a discouraging sight. A large group of Naga was moving in the city's direction..."
```suggestion
        	story= _ "On the road home, however, they came across a troubling sight. Massing to the south of their location was a large group of Naga intent on heading north towards Elefas..."
```

2021-09-20 23:23 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +        ## To be removed after testing
Still to be removed?

2021-09-20 23:24 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +        	## Fog and shroud
```suggestion
    	## Signpost image placement
        {PLACE_IMAGE scenery/signpost.png 20 1}
	## Number of enemies escaping variable
#ifdef EASY
	{VARIABLE noee 10}
#endif
#ifdef NORMAL
	{VARIABLE noee 7}
#endif
#ifdef HARD
	{VARIABLE noee 3}
#endif
	## Tree variable
	{VARIABLE tree_event_var 0}
        ## Fog and shroud
```

2021-09-20 23:24 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +            message = _ "I think we should make haste to the city, gather the guard and stop them at the mouth of the bay."
```suggestion
            message = _ "We should make haste to the city, gather the guard and stop them at the mouth of the bay."
```

2021-09-20 23:25 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +        	message= _ "Dont do anything stupid Cassih, we have to keep going."
```suggestion
        	message= _ "Don't do anything stupid Cassih, we have to keep going."
```

2021-09-20 23:26 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +		[/message]
```suggestion
	[message]
		speaker=Naga_2
		message= _ "Cassih, some of the merfolk villages would be a good source of supplies for our move north."
	[/message]
	[message]
		speaker=Kai
		message= _ "We cannot let them take our villages nor escape north! we have to stop them here and now. To arms!"
	[/message]
```

2021-09-20 23:29 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +            message= _ "Ouch, I cut myself with something pointy... Oh, it is a trident of some sort! It feels almost magical, maybe it belonged to a merman who could control lighning, should I pick
```suggestion
            message= _ "Ouch! I... cut myself. On what? Wait... this is a... trident of some sort! It feels almost magical. Should I pick it up?"
```

2021-09-20 23:29 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +            # message= _ "Wait, what's this? There's a... trident of some sort in the mud! Should I pick it up?"
```suggestion
```

2021-09-20 23:30 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +            	label= _ "A magical trident? I will be taking that."
```suggestion
            	label= _ "A magical trident? I'll take that!"
```

2021-09-20 23:30 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +                # label= _ "That sounds great! I’ll take it."
```suggestion
```

2021-09-20 23:31 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +            	label= _ "Fish and lightning do not mix well, I would prefer if someone else took it."
```suggestion
            	label= _ "Hmm... merfolk and lightning do not mesh well. Someone else should take it."
```

2021-09-20 23:31 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +                # label= _ "That sounds frightening. Let someone else have it."
```suggestion
```

2021-09-20 23:32 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +				[/command]
```suggestion
              	[command]
			[set_variable]
				name=get_trident
				value=visited
			[/set_variable]
		[/command]
```

2021-09-20 23:33 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +       	{EVENT_MOVETO_HANDLER get_trident 7 6 1 merman ( _ "Controlling lightning? I always wanted to do that!") ( _ "I am not fond of magical gadgets, I will not be taking the trident.") ({STORM_TRI
```suggestion
   {EVENT_MOVETO_HANDLER get_trident 7 6 1 merman ( _ "The ability to control lightning? That sounds amazing!") ( _ "I am not fond of magical gadgets...") ({STORM_TRIDENT 7 6 trident1}) yes ()}
```

2021-09-20 23:33 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +       	# I’ll just leave that trident where it is.
```suggestion
```

2021-09-20 23:35 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +            message= _ "My roots are deep... Yours flow with the water... I will not survive... Take this seed... plant it somewhere such that my life may go on..."
```suggestion
            message= _ "My roots are deep... Yours flow with the water. I can sense what you cannot... I will not survive. Take this seed... plant it somewhere such that my life may go on."
```

I know this isn't exactly what we settled on in the dialogue meeting, but I like this a bit better instead of using so many ellipses.

2021-09-20 23:36 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +                            message= _ "Oh no, that naga is heading to Elefas! I hope they can deal with him..."
```suggestion
                            message= _ "We've let one slip by! I hope the city guard can deal with him..."
```

2021-09-20 23:36 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +                            message= _ "More Naga are escaping, we have to do something to stop it!"
```suggestion
                            message= _ "Naga continue to escape! If we don't stop them now, the city may be in danger!"
```

2021-09-20 23:38 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +                            message= _ "If too many more of those naga go north, Elefas may not be prepared to repell an attack!"
```suggestion
                            message= _ "If too many more Naga head north, Elefas may not be prepared to repel an attack!"
```

2021-09-20 23:39 UTC, EIivaras commented on scenarios/02_along_the_way.cfg
> +                            message= _ "Oh no, that naga is heading to Elefas!"
```suggestion
                            message= _ "Oh no, that Naga may discover Elefas!"
```

2021-09-20 23:40 UTC, EIivaras requested changes
Lots of little spacing cleanup and dialogue adjustments that should go through before we merge :) Overall, good work!

2021-09-21 11:13 UTC, Descacharrado commented on scenarios/02_along_the_way.cfg
> +        ## To be removed after testing
True, recruit list is to be inherited from S01

2021-09-21 11:16 UTC, Descacharrado commented on scenarios/02_along_the_way.cfg
> +        	story= _ "But they came across a discouraging sight. A large group of Naga was moving in the city's direction..."
That is my problem with story telling, not being a native english speaker makes a weird cohesion.

2021-09-29 20:33 UTC, merged